# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='Subject_area',
            new_name='subject_area',
        ),
    ]
