# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20171007_2039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discussion',
        ),
        migrations.RemoveField(
            model_name='note',
            name='note_type',
        ),
    ]
