# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_auto_20171013_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
