# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_note_is_important'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_important',
        ),
    ]
