# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0006_auto_20171111_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_drive',
            field=models.CharField(default='put your drive link here', max_length=1000),
        ),
    ]
